# Backend Dockerfile for Python Flask App
FROM python:3.10-slim

WORKDIR /app
COPY backend/requirements.txt .

RUN apt-get update && apt-get install -y build-essential
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .
EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:create_app()"]
